### PR TITLE
M7ADA-302 Creating Form Sheet

### PR DESCRIPTION
**Pull request by balqishafiraini**
Merge all component to form sheet

### CODE REVIEW

**Review by williamchrisandy — CHANGES_REQUESTED** [review]
Refer to James's review.

**Review by jameschristianw — CHANGES_REQUESTED** [review]
Fixes needed:
- Padding (space) antara label dan text field
- inflationButton & recommendedButton dibuat dulu template function nya
- text field bisa terima prefix (buat Rp.)

**Review by jameschristianw — COMMENTED** [review]
@IBDesignable di PaddingLabel ngga terlalu kepake sih

**Comment by balqishafiraini** [comment]
Done semua ya @williamchrisandy @\

**Review by williamchrisandy — CHANGES_REQUESTED** [review]
- Layout meledak di layar kecil.
- DatePicker crash.
- Goal Term bukan input by user.

**Comment by balqishafiraini** [comment]
> * Layout meledak di layar kecil.
> * DatePicker crash.
> * Goal Term bukan input by user.

Layout: ScrollViewnya emg belom jalan. Jadi pas di layar kecil gabisa
Date picker: Emang belom add target
Goal term: Karena dia nyambungnya ke modal lagi, jadi cuma pure UI nya aja dulu

**Comment by jameschristianw** [comment]
> 

Yg gw liat
- Layout meledak bukan karena ScrollView
- Date picker udh add target, tapi salah implementasi
- Goal term klo emg gitu lu punya 2 pilihan, antara si TextField ga bs edit, atau ga pake TextField sama sekali

**Review by jameschristianw — CHANGES_REQUESTED** [review]
Benerin yg di comment yak

**Comment by williamchrisandy** [comment]
Approved.

**Review by jameschristianw — APPROVED** [review]
Ini kmrn sambil gw liatin sih, jd approve dr gw

**Review by williamchrisandy — CHANGES_REQUESTED** [review]
Included in DoD:
- No warning in code as well as in terminal (warning cause of xcode bug is okay, but still consult to Tech Member)

M7ADA-229:
- “Save” button is pressable IF every value in form is filled, else button is disabled
- “Save” button save the values to CoreData → Goal
- Modal/sheet is closed after successfully saving values to CoreData

M7ADA-230:
- Close modal and back to SetupPageView

M7ADA-218, M7ADA-221:
- TextField hanya menerima input dalam bentuk angka dari 1 hingga int32 (~2m). {NOTE BY WILLIAM CHRISANDY: KAYANYA HARUSNYA DODNYA DOUBLE SIH. CORE DATANYA DOUBLE SOALNYA. Maybe change to around 10^20 limitnya lebih make sense. 2M g make sense. Goal orang di 3M soalnya masih make sense}
- Changed value is saved to variable

M7ADA-231:
- Open modal/sheet to select goal recommendation

M7ADA-216, M7ADA-217:
- Changed date is saved to variable

M7ADA-219:
- Open modal/sheet to select Goal Term picker

M7ADA-220:
- Layout tidak berantakan di device dengan ukuran yang berbeda (iPhone SE)

Outside DoD:
- When press return in keyboard, close keyboard
- Use NavigationController/Fiks title (Terpotong di iPhone SE)
- Tambah icon (Gimana cara ganti icon or add icon?)
- Switch view harusnya beda file or buat jadi atribut class GoalModalView
- Inflation Detail button does not show after inflation amount
- Move to Inflation Detail when the button is pressed

**Pull request merged**
